const BH={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; rv:138.0) Gecko/20100101 Firefox/138.0",Accept:"application/json, text/plain, */*",Origin:"https://www.bseindia.com",Referer:"https://www.bseindia.com/"};
const r=await fetch("https://api.bseindia.com/BseIndiaAPI/api/getScripHeaderData/w?scripcode=500325",{headers:BH});
console.log("=== BSE getScripHeaderData ===");
console.log(JSON.stringify(await r.json(),null,1).slice(0,3000));
const H:Record<string,string>={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/118.0",Accept:"*/*",Referer:"https://www.nseindia.com/get-quotes/equity?symbol=TCS"};
let jar="";const p=await fetch("https://www.nseindia.com/get-quotes/equity?symbol=TCS",{headers:H,redirect:"follow"});
const a:any=p.headers;const l:string[]=typeof a.getSetCookie==="function"?a.getSetCookie():[];
jar=l.map(c=>c.split(";")[0]).join("; ");
const r2=await fetch("https://www.nseindia.com/api/historicalOR/generateSecurityWiseHistoricalData?from=20-07-2026&to=31-07-2026&symbol=TCS&type=priceVolumeDeliverable&series=EQ",{headers:{...H,Cookie:jar}});
const j2:any=await r2.json();
console.log("\n=== historicalOR rows:",j2?.data?.length,"===");
console.log(JSON.stringify(j2?.data?.[0],null,1));
