
import { auth } from "@/lib/better-auth/auth";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import AnalysisDashboard from "@/components/AnalysisDashboard";

export const metadata = {
  title: "Stock AI Analysis | TradeXpert",
  description: "Advanced AI-powered stock analysis and investment insights.",
};

export default async function AnalysisPage() {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  if (!session?.user) redirect("/sign-in");

  return (
    <div className="flex-1 w-full bg-[#0F0F0F] min-h-screen">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2 tracking-tight">AI Analysis</h1>
          <p className="text-gray-400">Get deep-dive investment reports generated by our multi-agent AI system.</p>
        </div>

        <AnalysisDashboard />
      </div>
    </div>
  );
}
